name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - main
      - fix/app-setup

permissions:
  pages: write
  id-token: write

jobs:
  upload-pages-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload site folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'site'

  deploy-pages:
    needs: upload-pages-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
